name: Validation Gate

on: 
  pull_request:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create pr_number.txt
        run: echo -e "11\n:rocket:" >> pr_number.txt

      - name: Upload pr_number.txt
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./pr_number.txt
